AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description :
  A Simple HelloWorld AWS Lambda example.

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.rout.HelloWorldHandler::handleRequest
      CodeUri: target/demo-aws-lambda-0.1.jar